In [27]:
import panel as pn
pn.extension('plotly')
import plotly.express as px
import pandas as pd
import hvplot.pandas
import matplotlib.pyplot as plt
import os
from pathlib import Path
import alpaca_trade_api as tradeapi
from dotenv import load_dotenv
from MCForecastTools import MCSimulation

In [42]:
alpaca_secret_key = 'rXoCM9s8Zug4baosmoqZ52Quo1HTE4APznEqHRdk'
alpaca_api_key = 'PKQ7AGGJ1RU7HOMRQRKM'

In [43]:
api = tradeapi.REST(
    alpaca_api_key,
    alpaca_secret_key,
    api_version = "v2"
)

In [44]:
# Import ETF Data
ARKF_path = Path('/Users/whitneyturner/Project-FI-Data/Performance_Data/Larry_Portfolio/ARKF.csv')
arkk_path = Path('/Users/whitneyturner/Project-FI-Data/Performance_Data/Larry_Portfolio/ARKK.csv')
arkq_path = Path('/Users/whitneyturner/Project-FI-Data/Performance_Data/Larry_Portfolio/ARKQ.csv')
arkf_data = pd.read_csv(ARKF_path, index_col="Date", parse_dates=True, infer_datetime_format=True)
arkk_data = pd.read_csv(arkk_path,index_col="Date", parse_dates=True, infer_datetime_format=True)
arkq_data = pd.read_csv(arkq_path,index_col="Date", parse_dates=True, infer_datetime_format=True)

In [45]:
#Import Larry's Portfolio data
aa_path = Path('/Users/whitneyturner/Project-FI-Data/Performance_Data/Larry_Portfolio/AA.csv')
aapl_path = Path('/Users/whitneyturner/Project-FI-Data/Performance_Data/Larry_Portfolio/AAPL.csv')
ai_path = Path('/Users/whitneyturner/Project-FI-Data/Performance_Data/Larry_Portfolio/AI.csv')
amc_path = Path('/Users/whitneyturner/Project-FI-Data/Performance_Data/Larry_Portfolio/AMC.csv')
amrs_path = Path('/Users/whitneyturner/Project-FI-Data/Performance_Data/Larry_Portfolio/AMRS.csv')
amzn_path = Path('/Users/whitneyturner/Project-FI-Data/Performance_Data/Larry_Portfolio/AMZN.csv')
baba_path = Path('/Users/whitneyturner/Project-FI-Data/Performance_Data/Larry_Portfolio/BABA.csv')
botz_path = Path('/Users/whitneyturner/Project-FI-Data/Performance_Data/Larry_Portfolio/BOTZ.csv')
crwd_path = Path('/Users/whitneyturner/Project-FI-Data/Performance_Data//Larry_Portfolio/CRWD.csv')
dal_path = Path('/Users/whitneyturner/Project-FI-Data/Performance_Data/Larry_Portfolio/DAL.csv')
etsy_path = Path('/Users/whitneyturner/Project-FI-Data/Performance_Data/Larry_Portfolio/ETSY.csv')
fvrr_path = Path('/Users/whitneyturner/Project-FI-Data/Performance_Data/Larry_Portfolio/FVRR.csv')
hl_path = Path('/Users/whitneyturner/Project-FI-Data/Performance_Data//Larry_Portfolio/HL.csv')
jnj_path = Path('/Users/whitneyturner/Project-FI-Data/Performance_Data/Larry_Portfolio/JNJ.csv')
jbl_path = Path('/Users/whitneyturner/Project-FI-Data/Performance_Data/Larry_Portfolio/JBL.csv')
lmnd_path = Path('/Users/whitneyturner/Project-FI-Data/Performance_Data/Larry_Portfolio/LMND.csv')
luv_path = Path('/Users/whitneyturner/Project-FI-Data/Performance_Data/Larry_Portfolio/LUV.csv')
mbd_path = Path('/Users/whitneyturner/Project-FI-Data/Performance_Data/Larry_Portfolio/MDB.csv')
mgni_path = Path('/Users/whitneyturner/Project-FI-Data/Performance_Data/Larry_Portfolio/MGNI.csv')
nio_path = Path('/Users/whitneyturner/Project-FI-Data/Performance_Data/Larry_Portfolio/NIO.csv')
pltr_path = Path('/Users/whitneyturner/Project-FI-Data/Performance_Data/Larry_Portfolio/PLTR.csv')
pton_path = Path('/Users/whitneyturner/Project-FI-Data/Performance_Data/Larry_Portfolio/PTON.csv')
pypl_path = Path('/Users/whitneyturner/Project-FI-Data/Performance_Data/Larry_Portfolio/PYPL.csv')
rgen_path = Path('/Users/whitneyturner/Project-FI-Data/Performance_Data/Larry_Portfolio/RGEN.csv')
sq_path = Path('/Users/whitneyturner/Project-FI-Data/Performance_Data/Larry_Portfolio/SQ.csv')
xom_path = Path('/Users/whitneyturner/Project-FI-Data/Performance_Data/Larry_Portfolio/XOM.csv')
wix_path = Path('/Users/whitneyturner/Project-FI-Data/Performance_Data/Larry_Portfolio/WIX.csv')
znga_path = Path('/Users/whitneyturner/Project-FI-Data/Performance_Data/Larry_Portfolio/ZNGA.csv')

In [46]:
#Create Data frames for larry's portfolio
aa_data = pd.read_csv(aa_path, index_col="Date", parse_dates=True, infer_datetime_format=True)
aapl_data = pd.read_csv(aapl_path,index_col="Date", parse_dates=True, infer_datetime_format=True)
ai_data = pd.read_csv(ai_path,index_col="Date", parse_dates=True, infer_datetime_format=True)
amc_data = pd.read_csv(amc_path, index_col="Date", parse_dates=True, infer_datetime_format=True)
amrs_data = pd.read_csv(amrs_path,index_col="Date", parse_dates=True, infer_datetime_format=True)
amzn_data = pd.read_csv(amzn_path,index_col="Date", parse_dates=True, infer_datetime_format=True)
baba_data = pd.read_csv(baba_path, index_col="Date", parse_dates=True, infer_datetime_format=True)
botz_data = pd.read_csv(botz_path,index_col="Date", parse_dates=True, infer_datetime_format=True)
crwd_data = pd.read_csv(crwd_path,index_col="Date", parse_dates=True, infer_datetime_format=True)
dal_data = pd.read_csv(dal_path, index_col="Date", parse_dates=True, infer_datetime_format=True)
etsy_data = pd.read_csv(etsy_path,index_col="Date", parse_dates=True, infer_datetime_format=True)
fvrr_data = pd.read_csv(fvrr_path,index_col="Date", parse_dates=True, infer_datetime_format=True)
hl_data = pd.read_csv(hl_path, index_col="Date", parse_dates=True, infer_datetime_format=True)
jnj_data = pd.read_csv(jnj_path,index_col="Date", parse_dates=True, infer_datetime_format=True)
jbl_data = pd.read_csv(jbl_path,index_col="Date", parse_dates=True, infer_datetime_format=True)
lmnd_data = pd.read_csv(lmnd_path, index_col="Date", parse_dates=True, infer_datetime_format=True)
luv_data = pd.read_csv(luv_path,index_col="Date", parse_dates=True, infer_datetime_format=True)
mbd_data = pd.read_csv(mbd_path,index_col="Date", parse_dates=True, infer_datetime_format=True)
mgni_data = pd.read_csv(mgni_path, index_col="Date", parse_dates=True, infer_datetime_format=True)
nio_data = pd.read_csv(nio_path,index_col="Date", parse_dates=True, infer_datetime_format=True)
pltr_data = pd.read_csv(pltr_path,index_col="Date", parse_dates=True, infer_datetime_format=True)
pton_data = pd.read_csv(pton_path, index_col="Date", parse_dates=True, infer_datetime_format=True)
pypl_data = pd.read_csv(pypl_path,index_col="Date", parse_dates=True, infer_datetime_format=True)
rgen_data = pd.read_csv(rgen_path,index_col="Date", parse_dates=True, infer_datetime_format=True)
sq_data = pd.read_csv(sq_path, index_col="Date", parse_dates=True, infer_datetime_format=True)
xom_data = pd.read_csv(xom_path,index_col="Date", parse_dates=True, infer_datetime_format=True)
wix_data = pd.read_csv(wix_path,index_col="Date", parse_dates=True, infer_datetime_format=True)
znga_data = pd.read_csv(znga_path,index_col="Date", parse_dates=True, infer_datetime_format=True)

In [47]:
#Update Larry's stock data to show only the closing price
aa_close = aa_data['Close']
aapl_close = aapl_data['Close']
ai_close = ai_data['Close']
amc_close = amc_data['Close']
amrs_close = amrs_data['Close']
amzn_close = amzn_data['Close']
baba_close = baba_data['Close']
botz_close = botz_data['Close']
crwd_close = crwd_data['Close']
dal_close = dal_data['Close']
etsy_close = etsy_data['Close']
fvrr_close = fvrr_data['Close']
hl_close = hl_data['Close']
jbl_close = jbl_data['Close']
jnj_close = jnj_data['Close']
lmnd_close = lmnd_data['Close']
luv_close = luv_data['Close']
mbd_close = mbd_data['Close']
mgni_close = mgni_data['Close']
nio_close = nio_data['Close']
pltr_close = pltr_data['Close']
pton_close = pton_data['Close']
pypl_close = pypl_data['Close']
rgen_close = rgen_data['Close']
sq_close = sq_data['Close']
wix_close = wix_data['Close']
xom_close = xom_data['Close']
znga_close = znga_data['Close']

In [48]:
# Find Larry' stock portfolio daily Returns
aa_daily_returns = pd.DataFrame(aa_close.pct_change())
aapl_daily_returns = pd.DataFrame(aapl_close.pct_change())
ai_daily_returns = pd.DataFrame(ai_close.pct_change())
amc_daily_returns = pd.DataFrame(amc_close.pct_change())
amrs_daily_returns = pd.DataFrame(amrs_close.pct_change())
amzn_daily_returns = pd.DataFrame(amzn_close.pct_change())
baba_daily_returns = pd.DataFrame(baba_close.pct_change())
botz_daily_returns = pd.DataFrame(botz_close.pct_change())
crwd_daily_returns = pd.DataFrame(crwd_close.pct_change())
dal_daily_returns = pd.DataFrame(dal_close.pct_change())
etsy_daily_returns = pd.DataFrame(etsy_close.pct_change())
fvrr_daily_returns = pd.DataFrame(fvrr_close.pct_change())
hl_daily_returns = pd.DataFrame(hl_close.pct_change())
jbl_daily_returns = pd.DataFrame(jbl_close.pct_change())
jnj_daily_returns = pd.DataFrame(jnj_close.pct_change())
lmnd_daily_returns = pd.DataFrame(lmnd_close.pct_change())
luv_daily_returns = pd.DataFrame(luv_close.pct_change())
mbd_daily_returns = pd.DataFrame(mbd_close.pct_change())
mgni_daily_returns = pd.DataFrame(mgni_close.pct_change())
nio_daily_returns = pd.DataFrame(nio_close.pct_change())
pltr_daily_returns = pd.DataFrame(pltr_close.pct_change())
pton_daily_returns = pd.DataFrame(pton_close.pct_change())
pypl_daily_returns = pd.DataFrame(pypl_close.pct_change())
rgen_daily_returns = pd.DataFrame(rgen_close.pct_change())
sq_daily_returns = pd.DataFrame(sq_close.pct_change())
wix_daily_returns = pd.DataFrame(wix_close.pct_change())
xom_daily_returns = pd.DataFrame(xom_close.pct_change())
znga_daily_returns = pd.DataFrame(znga_close.pct_change())

In [49]:
#update column names to reflect each stock and combine into one data Frame
aa_daily_returns1 = aa_daily_returns.rename(columns={'Close': 'AA'})
aapl_daily_returns1 = aapl_daily_returns.rename(columns={'Close': 'AAPL'})
ai_daily_returns1 = ai_daily_returns.rename(columns={'Close': 'AI'})
amc_daily_returns1 = amc_daily_returns.rename(columns={'Close': 'AMC'})
amrs_daily_returns1 = amrs_daily_returns.rename(columns={'Close': 'AMRS'})
amzn_daily_returns1 = amzn_daily_returns.rename(columns={'Close': 'AMZN'})
baba_daily_returns1 = baba_daily_returns.rename(columns={'Close': 'BABA'})
botz_daily_returns1 = botz_daily_returns.rename(columns={'Close': 'BOTZ'})
crwd_daily_returns1 = crwd_daily_returns.rename(columns={'Close': 'CRWD'})
dal_daily_returns1 = dal_daily_returns.rename(columns={'Close': 'DAL'})
etsy_daily_returns1 = etsy_daily_returns.rename(columns={'Close': 'ETSY'})
fvrr_daily_returns1 = fvrr_daily_returns.rename(columns={'Close': 'FVRR'})
hl_daily_returns1 = hl_daily_returns.rename(columns={'Close': 'HL'})
jbl_daily_returns1 = jbl_daily_returns.rename(columns={'Close': 'JBL'})
jnj_daily_returns1 = jnj_daily_returns.rename(columns={'Close': 'JNJ'})
lmnd_daily_returns1 = lmnd_daily_returns.rename(columns={'Close': 'LMND'})
luv_daily_returns1 = luv_daily_returns.rename(columns={'Close': 'LUV'})
mbd_daily_returns1 = mbd_daily_returns.rename(columns={'Close': 'MBD'})
mgni_daily_returns1 = mgni_daily_returns.rename(columns={'Close': 'MGNI'})
nio_daily_returns1 = nio_daily_returns.rename(columns={'Close': 'NIO'})
pltr_daily_returns1 = pltr_daily_returns.rename(columns={'Close': 'PLTR'})
pton_daily_returns1 = pton_daily_returns.rename(columns={'Close': 'PTON'})
pypl_daily_returns1 = pypl_daily_returns.rename(columns={'Close': 'PYPL'})
rgen_daily_returns1 = rgen_daily_returns.rename(columns={'Close': 'RGEN'})
sq_daily_returns1 = sq_daily_returns.rename(columns={'Close': 'SQ'})
wix_daily_returns1 = wix_daily_returns.rename(columns={'Close': 'WIX'})
xom_daily_returns1 = xom_daily_returns.rename(columns={'Close': 'XOM'})
znga_daily_returns1 = znga_daily_returns.rename(columns={'Close': 'ZNGA'})
larry_portfolio_df = pd.concat([aa_daily_returns1, aapl_daily_returns1, ai_daily_returns1, amc_daily_returns1, amrs_daily_returns1, amzn_daily_returns1, baba_daily_returns1, botz_daily_returns1, crwd_daily_returns1, dal_daily_returns1, etsy_daily_returns1, fvrr_daily_returns1, hl_daily_returns1, jbl_daily_returns1, jnj_daily_returns1, lmnd_daily_returns1, luv_daily_returns1, mbd_daily_returns1, mgni_daily_returns1, nio_daily_returns1, pltr_daily_returns1, pton_daily_returns1, pypl_daily_returns1, rgen_daily_returns1, sq_daily_returns1, wix_daily_returns1, xom_daily_returns1, znga_daily_returns1], axis = 'columns', join = 'inner').dropna()
larry_portfolio_df.head()

,AA,AAPL,AI,AMC,AMRS,AMZN,BABA,BOTZ,CRWD,DAL,...,MGNI,NIO,PLTR,PTON,PYPL,RGEN,SQ,WIX,XOM,ZNGA
Date,,,,,,,,,,,,,,,,,,,,,
2020-12-10 16:00:00,0.057244,0.011989,0.405557,0.059585,0.038835,-0.000873,0.004056,0.000000,0.083168,0.012111,...,0.049030,0.027494,0.015396,0.064988,0.021537,0.004195,0.049314,0.094695,0.028271,0.004640
2020-12-11 16:00:00,-0.048730,-0.006735,-0.080154,-0.041565,0.087227,0.004814,-0.001246,-0.003733,-0.022612,-0.020648,...,-0.002568,-0.071650,0.005917,-0.007543,-0.005944,0.007631,-0.003038,-0.019759,-0.004772,0.003464
2020-12-14 16:00:00,-0.047285,-0.005147,-0.144004,-0.186224,-0.065903,0.013012,-0.032169,0.007181,-0.012051,-0.025156,...,-0.034501,-0.023821,0.001471,0.041076,0.031440,0.017634,-0.003370,-0.020532,-0.036073,0.002301
2020-12-15 16:00:00,0.018842,0.050090,-0.003517,-0.103448,0.049080,0.002582,-0.003593,0.010539,0.006502,0.028508,...,-0.010667,0.061493,-0.029736,0.048150,0.003669,0.008257,0.019133,0.000000,0.019422,0.047072
2020-12-16 16:00:00,-0.026613,-0.000547,0.114608,-0.027972,0.204678,0.023961,0.026577,-0.003067,0.027783,-0.018399,...,0.059838,0.026897,-0.019296,0.048677,0.038809,-0.016863,0.032229,0.026711,0.015335,0.043860

In [50]:
#Import Joe's Fidelity Stock data
csv_path_AAPL= Path("/Users/whitneyturner/Project-FI-Data/Joe's_Fidelity_Stock_Data/Resources/AAPL.csv")
csv_path_AUY= Path("/Users/whitneyturner/Project-FI-Data/Joe's_Fidelity_Stock_Data/Resources/AUY.csv")
csv_path_BABA= Path("/Users/whitneyturner/Project-FI-Data/Joe's_Fidelity_Stock_Data/Resources/BABA.csv")
csv_path_BLMN= Path("/Users/whitneyturner/Project-FI-Data/Joe's_Fidelity_Stock_Data/Resources/BLMN.csv")
csv_path_BOTZ= Path("/Users/whitneyturner/Project-FI-Data/Joe's_Fidelity_Stock_Data/Resources/BOTZ.csv")
csv_path_CAT= Path("/Users/whitneyturner/Project-FI-Data/Joe's_Fidelity_Stock_Data/Resources/CAT.csv")
csv_path_CMPS= Path("/Users/whitneyturner/Project-FI-Data/Joe's_Fidelity_Stock_Data/Resources/CMPS.csv")
csv_path_CROX= Path("/Users/whitneyturner/Project-FI-Data/Joe's_Fidelity_Stock_Data/Resources/CROX.csv")
csv_path_CRWD= Path("/Users/whitneyturner/Project-FI-Data/Joe's_Fidelity_Stock_Data/Resources/CRWD.csv")
csv_path_CROX= Path("/Users/whitneyturner/Project-FI-Data/Joe's_Fidelity_Stock_Data/Resources/CROX.csv")
csv_path_DAL= Path("/Users/whitneyturner/Project-FI-Data/Joe's_Fidelity_Stock_Data/Resources/DAL.csv")
csv_path_EGO= Path("/Users/whitneyturner/Project-FI-Data/Joe's_Fidelity_Stock_Data/Resources/EGO.csv")
csv_path_FCX= Path("/Users/whitneyturner/Project-FI-Data/Joe's_Fidelity_Stock_Data/Resources/FCX.csv")
csv_path_GM= Path("/Users/whitneyturner/Project-FI-Data/Joe's_Fidelity_Stock_Data/Resources/GM.csv")
csv_path_GPS= Path("/Users/whitneyturner/Project-FI-Data/Joe's_Fidelity_Stock_Data/Resources/GPS.csv")
csv_path_INO= Path("/Users/whitneyturner/Project-FI-Data/Joe's_Fidelity_Stock_Data/Resources/INO.csv")
csv_path_LLY= Path("/Users/whitneyturner/Project-FI-Data/Joe's_Fidelity_Stock_Data/Resources/LLY.csv")
csv_path_LUV= Path("/Users/whitneyturner/Project-FI-Data/Joe's_Fidelity_Stock_Data/Resources/LUV.csv")
csv_path_MGNI= Path("/Users/whitneyturner/Project-FI-Data/Joe's_Fidelity_Stock_Data/Resources/MGNI.csv")
csv_path_MRVL= Path("/Users/whitneyturner/Project-FI-Data/Joe's_Fidelity_Stock_Data/Resources/MRVL.csv")
csv_path_NIO= Path("/Users/whitneyturner/Project-FI-Data/Joe's_Fidelity_Stock_Data/Resources/NIO.csv")
csv_path_PTON= Path("/Users/whitneyturner/Project-FI-Data/Joe's_Fidelity_Stock_Data/Resources/PTON.csv")
csv_path_SNOW= Path("/Users/whitneyturner/Project-FI-Data/Joe's_Fidelity_Stock_Data/Resources/SNOW.csv")
csv_path_SONO= Path("/Users/whitneyturner/Project-FI-Data/Joe's_Fidelity_Stock_Data/Resources/SONO.csv")
csv_path_SQ= Path("/Users/whitneyturner/Project-FI-Data/Joe's_Fidelity_Stock_Data/Resources/SQ.csv")
csv_path_TACO= Path("/Users/whitneyturner/Project-FI-Data/Joe's_Fidelity_Stock_Data/Resources/TACO.csv")
csv_path_TMUS= Path("/Users/whitneyturner/Project-FI-Data/Joe's_Fidelity_Stock_Data/Resources/TMUS.csv")
csv_path_UNH= Path("/Users/whitneyturner/Project-FI-Data/Joe's_Fidelity_Stock_Data/Resources/UNH.csv")
csv_path_UTZ= Path("/Users/whitneyturner/Project-FI-Data/Joe's_Fidelity_Stock_Data/Resources/UTZ.csv")
csv_path_VSTO= Path("/Users/whitneyturner/Project-FI-Data/Joe's_Fidelity_Stock_Data/Resources/VSTO.csv")
csv_path_WORK= Path("/Users/whitneyturner/Project-FI-Data/Joe's_Fidelity_Stock_Data/Resources/WORK.csv")
csv_path_XOM= Path("/Users/whitneyturner/Project-FI-Data/Joe's_Fidelity_Stock_Data/Resources/XOM.csv")

In [51]:
#Read in Joe's Fidelty data
df_AAPL = pd.read_csv(csv_path_AAPL, index_col= 'Date',parse_dates=True,infer_datetime_format=True)
df_AUY = pd.read_csv(csv_path_AUY, index_col= 'Date',parse_dates=True,infer_datetime_format=True)
df_BABA = pd.read_csv(csv_path_BABA, index_col= 'Date',parse_dates=True,infer_datetime_format=True)
df_BLMN = pd.read_csv(csv_path_BLMN, index_col= 'Date',parse_dates=True,infer_datetime_format=True)
df_BOTZ = pd.read_csv(csv_path_BOTZ, index_col= 'Date',parse_dates=True,infer_datetime_format=True)
df_CAT = pd.read_csv(csv_path_CAT, index_col= 'Date',parse_dates=True,infer_datetime_format=True)
df_CMPS = pd.read_csv(csv_path_CMPS, index_col= 'Date',parse_dates=True,infer_datetime_format=True)
df_CROX = pd.read_csv(csv_path_CROX, index_col= 'Date',parse_dates=True,infer_datetime_format=True)
df_CRWD = pd.read_csv(csv_path_CRWD, index_col= 'Date',parse_dates=True,infer_datetime_format=True)
df_DAL = pd.read_csv(csv_path_DAL, index_col= 'Date',parse_dates=True,infer_datetime_format=True)
df_EGO = pd.read_csv(csv_path_EGO, index_col= 'Date',parse_dates=True,infer_datetime_format=True)
df_FCX = pd.read_csv(csv_path_FCX, index_col= 'Date',parse_dates=True,infer_datetime_format=True)
df_GM = pd.read_csv(csv_path_GM, index_col= 'Date',parse_dates=True,infer_datetime_format=True)
df_GPS = pd.read_csv(csv_path_GPS, index_col= 'Date',parse_dates=True,infer_datetime_format=True)
df_INO = pd.read_csv(csv_path_INO, index_col= 'Date',parse_dates=True,infer_datetime_format=True)
df_LLY = pd.read_csv(csv_path_LLY, index_col= 'Date',parse_dates=True,infer_datetime_format=True)
df_LUV = pd.read_csv(csv_path_LUV, index_col= 'Date',parse_dates=True,infer_datetime_format=True)
df_MGNI = pd.read_csv(csv_path_MGNI, index_col= 'Date',parse_dates=True,infer_datetime_format=True)
df_MRVL = pd.read_csv(csv_path_MRVL, index_col= 'Date',parse_dates=True,infer_datetime_format=True)
df_NIO = pd.read_csv(csv_path_NIO, index_col= 'Date',parse_dates=True,infer_datetime_format=True)
df_PTON = pd.read_csv(csv_path_PTON, index_col= 'Date',parse_dates=True,infer_datetime_format=True)
df_SNOW = pd.read_csv(csv_path_SNOW, index_col= 'Date',parse_dates=True,infer_datetime_format=True)
df_SONO = pd.read_csv(csv_path_SONO, index_col= 'Date',parse_dates=True,infer_datetime_format=True)
df_SQ = pd.read_csv(csv_path_SQ, index_col= 'Date',parse_dates=True,infer_datetime_format=True)
df_TACO = pd.read_csv(csv_path_TACO, index_col= 'Date',parse_dates=True,infer_datetime_format=True)
df_TMUS = pd.read_csv(csv_path_TMUS, index_col= 'Date',parse_dates=True,infer_datetime_format=True)
df_UNH = pd.read_csv(csv_path_UNH, index_col= 'Date',parse_dates=True,infer_datetime_format=True)
df_UTZ = pd.read_csv(csv_path_UTZ, index_col= 'Date',parse_dates=True,infer_datetime_format=True)
df_VSTO = pd.read_csv(csv_path_VSTO, index_col= 'Date',parse_dates=True,infer_datetime_format=True)
df_WORK = pd.read_csv(csv_path_WORK, index_col= 'Date',parse_dates=True,infer_datetime_format=True)
df_XOM = pd.read_csv(csv_path_XOM, index_col= 'Date',parse_dates=True,infer_datetime_format=True)

In [52]:
#find Joe's Fidelity Stock portfolio daily returns
df_AAPL_close = df_AAPL['Close']
df_AUY_close = df_AUY['Close']
df_BABA_close = df_BABA['Close']
df_BLMN_close = df_BLMN['Close']
df_BOTZ_close = df_BOTZ['Close']
df_CAT_close = df_CAT['Close']
df_CMPS_close = df_CMPS['Close']
df_CROX_close = df_CROX['Close']
df_CRWD_close = df_CRWD['Close']
df_DAL_close = df_DAL['Close']
df_EGO_close = df_EGO['Close']
df_FCX_close = df_FCX['Close']
df_GM_close = df_GM['Close']
df_GPS_close = df_GPS['Close']
df_INO_close = df_INO['Close']
df_LLY_close = df_LLY['Close']
df_LUV_close = df_LUV['Close']
df_MGNI_close = df_MGNI['Close']
df_MRVL_close = df_MRVL['Close']
df_NIO_close = df_NIO['Close']
df_PTON_close = df_PTON['Close']
df_SNOW_close = df_SNOW['Close']
df_SONO_close = df_SONO['Close']
df_SQ_close = df_SQ['Close']
df_TACO_close = df_TACO['Close']
df_TMUS_close = df_TMUS['Close']
df_UNH_close = df_UNH['Close']
df_UTZ_close = df_UTZ['Close']
df_VSTO_close = df_VSTO['Close']
df_WORK_close = df_WORK['Close']
df_XOM_close = df_XOM['Close']

In [53]:
#Joe's Fidelity stock portfolio daily Returns Continued
aapl_daily_returns = pd.DataFrame(df_AAPL_close.pct_change())
auy_daily_returns = pd.DataFrame(df_AUY_close.pct_change())
baba_daily_returns = pd.DataFrame(df_BABA_close.pct_change())
blmn_daily_returns = pd.DataFrame(df_BLMN_close.pct_change())
botz_daily_returns = pd.DataFrame(df_BOTZ_close.pct_change())
cat_daily_returns = pd.DataFrame(df_CAT_close.pct_change())
cmps_daily_returns = pd.DataFrame(df_CMPS_close.pct_change())
crox_daily_returns = pd.DataFrame(df_CROX_close.pct_change())
crwd_daily_returns = pd.DataFrame(df_CRWD_close.pct_change())
dal_daily_returns = pd.DataFrame(df_DAL_close.pct_change())
ego_daily_returns = pd.DataFrame(df_EGO_close.pct_change())
fcx_daily_returns = pd.DataFrame(df_FCX_close.pct_change())
gm_daily_returns = pd.DataFrame(df_GM_close.pct_change())
gps_daily_returns = pd.DataFrame(df_GPS_close.pct_change())
ino_daily_returns = pd.DataFrame(df_INO_close.pct_change())
lly_daily_returns = pd.DataFrame(df_LLY_close.pct_change())
luv_daily_returns = pd.DataFrame(df_LUV_close.pct_change())
mgni_daily_returns = pd.DataFrame(df_MGNI_close.pct_change())
mrvl_daily_returns = pd.DataFrame(df_MRVL_close.pct_change())
nio_daily_returns = pd.DataFrame(df_NIO_close.pct_change())
pton_daily_returns = pd.DataFrame(df_PTON_close.pct_change())
snow_daily_returns = pd.DataFrame(df_SNOW_close.pct_change())
sono_daily_returns = pd.DataFrame(df_SONO_close.pct_change())
sq_daily_returns = pd.DataFrame(df_SQ_close.pct_change())
taco_daily_returns = pd.DataFrame(df_TACO_close.pct_change())
tmus_daily_returns = pd.DataFrame(df_TMUS_close.pct_change())
unh_daily_returns = pd.DataFrame(df_UNH_close.pct_change())
utz_daily_returns = pd.DataFrame(df_UTZ_close.pct_change())
vsto_daily_returns = pd.DataFrame(df_VSTO_close.pct_change())
work_daily_returns = pd.DataFrame(df_WORK_close.pct_change())
xom_daily_returns = pd.DataFrame(df_XOM_close.pct_change())

In [54]:
#update column names to reflect each stock
aapl_daily_returns1 = aapl_daily_returns.rename(columns={'Close': 'AAPL'})
auy_daily_returns1 = auy_daily_returns.rename(columns={'Close': 'AUY'})
baba_daily_returns1 = baba_daily_returns.rename(columns={'Close': 'BABA'})
blmn_daily_returns1 = blmn_daily_returns.rename(columns={'Close': 'BLMN'})
botz_daily_returns1 = botz_daily_returns.rename(columns={'Close': 'BOTZ'})
cat_daily_returns1 = cat_daily_returns.rename(columns={'Close': 'CAT'})
cmps_daily_returns1 = cmps_daily_returns.rename(columns={'Close': 'CMPS'})
crox_daily_returns1 = crox_daily_returns.rename(columns={'Close': 'CROX'})
crwd_daily_returns1 = crwd_daily_returns.rename(columns={'Close': 'CRWD'})
dal_daily_returns1 = dal_daily_returns.rename(columns={'Close': 'DAL'})
ego_daily_returns1 = ego_daily_returns.rename(columns={'Close': 'EGO'})
fcx_daily_returns1 = fcx_daily_returns.rename(columns={'Close': 'FCX'})
gm_daily_returns1 = gm_daily_returns.rename(columns={'Close': 'GM'})
gps_daily_returns1 = gps_daily_returns.rename(columns={'Close': 'GPS'})
ino_daily_returns1 = ino_daily_returns.rename(columns={'Close': 'INO'})
lly_daily_returns1 = lly_daily_returns.rename(columns={'Close': 'LLY'})
luv_daily_returns1 = luv_daily_returns.rename(columns={'Close': 'LUV'})
mgni_daily_returns1 = mgni_daily_returns.rename(columns={'Close': 'MGNI'})
mrvl_daily_returns1 = mrvl_daily_returns.rename(columns={'Close': 'MRVL'})
nio_daily_returns1 = nio_daily_returns.rename(columns={'Close': 'NIO'})
pton_daily_returns1 = pton_daily_returns.rename(columns={'Close': 'PTON'})
snow_daily_returns1 = snow_daily_returns.rename(columns={'Close': 'SNOW'})
sono_daily_returns1 = sono_daily_returns.rename(columns={'Close': 'SONO'})
sq_daily_returns1 = sq_daily_returns.rename(columns={'Close': 'SQ'})
taco_daily_returns1 = taco_daily_returns.rename(columns={'Close': 'TACO'})
tmus_daily_returns1 = tmus_daily_returns.rename(columns={'Close': 'TMUS'})
unh_daily_returns1 = unh_daily_returns.rename(columns={'Close': 'UNH'})
utz_daily_returns1 = utz_daily_returns.rename(columns={'Close': 'UTZ'})
vsto_daily_returns1 = vsto_daily_returns.rename(columns={'Close': 'VSTO'})
work_daily_returns1 = work_daily_returns.rename(columns={'Close': 'WORK'})
xom_daily_returns1 = xom_daily_returns.rename(columns={'Close': 'XOM'})

In [55]:
# create Data frame for Joe's Fidelity Portfolio 
joe_fidelity_portfolio_df = pd.concat([aapl_daily_returns1, 
                                       auy_daily_returns1, 
                                       baba_daily_returns1, 
                                       blmn_daily_returns1, 
                                       botz_daily_returns1, 
                                       cat_daily_returns1,
                                       cmps_daily_returns1, 
                                       crox_daily_returns1, 
                                       crwd_daily_returns1, 
                                       dal_daily_returns1, 
                                       ego_daily_returns1, 
                                       fcx_daily_returns1, 
                                       gm_daily_returns1, 
                                       gps_daily_returns1, 
                                       ino_daily_returns1, 
                                       lly_daily_returns1, 
                                       luv_daily_returns1, 
                                       mgni_daily_returns1, 
                                       mrvl_daily_returns1, 
                                       nio_daily_returns1, 
                                       pton_daily_returns1, 
                                       snow_daily_returns1,
                                       sono_daily_returns1,
                                       sq_daily_returns1, 
                                       taco_daily_returns1, 
                                       tmus_daily_returns1, 
                                       unh_daily_returns1, 
                                       utz_daily_returns1, 
                                       vsto_daily_returns1, 
                                       work_daily_returns1, 
                                       xom_daily_returns1], axis = 'columns', join = 'inner').dropna()

In [56]:
# Larry's & Joe's Weights 
larry_weights = [0.041060877,0.038166997, 0.040336811,0.080258084, 0.000728936, 0.046117532, 0.043762719, 0.017763899,0.006075988,0.037826406,0.02389707,0.007337461,0.022526607,0.000458904,0.017958247,0.005738641,0.014704163,0.030825717,0.014515591,0.015495521,0.120349752,0.038249083,0.023164878,0.015018582,0.0556435,0.062648952, 0.02596364,0.055374621,0.039345999,0.000764506,0.036377883,0.021542432]

joe_weights = [0.05581013342,
0.009432909158,
0.4312329417,
0.003238980958,
0.005784321686,
0.0338887103,
0.007777540736,
0.01215365316,
0.01461926513,
0.008814014643,
0.00947177693,
0.01505876993,
0.05277047437,
0.001969300422,
0.00445285136,
0.004969104063,
0.003862858521,
0.009423939672,
0.007325080012,
0.01253934105,
0.04484742864,
0.09766773349,
0.003163238634,
0.02048331558,
0.00921963472,
0.03618589526,
0.03225925373,
0.009118977158,
0.006688246525,
0.02535374633,
0.01041656276]

In [57]:
### Joe's Simulations Data frame
# Set timeframe to '1D'
timeframe = "1D"

# Set start and end datetimes between now and 5 years ago.
start_date = pd.Timestamp("2018-05-24", tz="America/New_York").isoformat()
end_date = pd.Timestamp("2021-05-24", tz="America/New_York").isoformat()

# Set the ticker information
tickers = ["GM","TACO","AUY","WORK","AAPL"]

# Get 5 year's worth of historical price data
joes_ticker = api.get_barset(
    tickers,
    timeframe,
    start=start_date,
    end=end_date,
    limit=1000
).df

# Display sample data
joes_ticker.head()

                             AAPL                                     AUY  \
                             open    high     low   close    volume  open
time
2018-05-24 00:00:00-04:00  188.77  188.84  186.21  188.21  15019898  2.84
2018-05-25 00:00:00-04:00  188.23  189.65  187.65  188.58  13702107  2.90
2018-05-29 00:00:00-04:00  187.60  188.75  186.87  187.86  17042382  2.83
2018-05-30 00:00:00-04:00  187.72  188.00  186.78  187.50  14392159  2.88
2018-05-31 00:00:00-04:00  187.25  188.23  186.14  186.88  16629099  2.91

                                                        ...   TACO         \
                           high     low close   volume  ...   open   high
time                                                    ...
2018-05-24 00:00:00-04:00  2.92  2.8258  2.91  8418694  ...  11.77  11.84
2018-05-25 00:00:00-04:00  2.94  2.8600  2.86  8681001  ...  11.54  12.17
2018-05-29 00:00:00-04:00  2.90  2.8100  2.87  6205123  ...  12.05  12.12
2018-05-30 00:00:00-04:00  2.95  2.8730  2.91  7032656  ...  11.90  12.23
2018-05-31 00:00:00-04:00  2.94  2.8900  2.92  8482293  ...  12.26  12.43

                                                  WORK
                             low  close    volume open high low close volume
time
2018-05-24 00:00:00-04:00  11.53  11.55  183250.0  NaN  NaN NaN   NaN    NaN
2018-05-25 00:00:00-04:00  11.54  12.07  409256.0  NaN  NaN NaN   NaN    NaN
2018-05-29 00:00:00-04:00  11.79  11.89  198195.0  NaN  NaN NaN   NaN    NaN
2018-05-30 00:00:00-04:00  11.90  12.21  187752.0  NaN  NaN NaN   NaN    NaN
2018-05-31 00:00:00-04:00  12.00  12.03  149811.0  NaN  NaN NaN   NaN    NaN

[5 rows x 25 columns]

In [58]:
##Larry' Simulation data frame
# Set timeframe to '1D'
timeframe = "1D"

# Set start and end datetimes between now and 5 years ago.
start_date = pd.Timestamp("2018-05-24", tz="America/New_York").isoformat()
end_date = pd.Timestamp("2021-05-24", tz="America/New_York").isoformat()

# Set the ticker information
larrys_tickers = ['AA', 'NIO', 'PFE', 'XOM', 'ZNGA']

# Get 5 year's worth of historical price data
larrys_ticker = api.get_barset(
    larrys_tickers,
    timeframe,
    start=start_date,
    end=end_date,
    limit=1000
).df

# Display sample data
larrys_ticker.head()

                              AA                                 NIO           \
                            open    high    low  close   volume open high low
time
2018-05-24 00:00:00-04:00  48.62  49.440  48.55  49.15  1132704  NaN  NaN NaN
2018-05-25 00:00:00-04:00  48.74  48.825  47.66  47.92  2154178  NaN  NaN NaN
2018-05-29 00:00:00-04:00  47.57  47.950  46.82  47.30  1599177  NaN  NaN NaN
2018-05-30 00:00:00-04:00  48.11  48.660  47.50  48.54  1353344  NaN  NaN NaN
2018-05-31 00:00:00-04:00  49.98  50.430  47.81  48.06  2899262  NaN  NaN NaN

                                        ...    XOM                       \
                          close volume  ...   open   high    low  close
time                                    ...
2018-05-24 00:00:00-04:00   NaN    NaN  ...  81.35  81.36  79.95  80.26
2018-05-25 00:00:00-04:00   NaN    NaN  ...  79.28  79.33  78.09  78.70
2018-05-29 00:00:00-04:00   NaN    NaN  ...  78.15  78.73  77.53  78.40
2018-05-30 00:00:00-04:00   NaN    NaN  ...  79.25  81.66  79.22  81.51
2018-05-31 00:00:00-04:00   NaN    NaN  ...  80.81  81.55  80.69  81.24

                                     ZNGA
                             volume  open   high    low close    volume
time
2018-05-24 00:00:00-04:00   9966548  4.14  4.185  4.070  4.15   7431723
2018-05-25 00:00:00-04:00  10994921  4.12  4.220  4.110  4.18   6848868
2018-05-29 00:00:00-04:00  10346262  4.16  4.190  4.130  4.19   5380287
2018-05-30 00:00:00-04:00  12728594  4.20  4.430  4.200  4.33  24457856
2018-05-31 00:00:00-04:00   9428701  4.34  4.520  4.331  4.41  23173555

[5 rows x 25 columns]

In [59]:
# Configure a Monte Carlo simulation to forecast twenty years cumulative returns for Joe's Portfolio
joes_MC_even_dist = MCSimulation(
    portfolio_data = joes_ticker,
    weights = [.2, .2, .2, .2, .2],
    num_simulation = 500,
    num_trading_days = 252*20
)

In [61]:
# Run a Monte Carlo simulation to forecast twenty years cumulative returns
joes_MC_even_dist.calc_cumulative_return()

Running Monte Carlo simulation number 0.
Running Monte Carlo simulation number 10.
Running Monte Carlo simulation number 20.
Running Monte Carlo simulation number 30.
Running Monte Carlo simulation number 40.
Running Monte Carlo simulation number 50.
Running Monte Carlo simulation number 60.
Running Monte Carlo simulation number 70.
Running Monte Carlo simulation number 80.
Running Monte Carlo simulation number 90.
Running Monte Carlo simulation number 100.
Running Monte Carlo simulation number 110.
Running Monte Carlo simulation number 120.
Running Monte Carlo simulation number 130.
Running Monte Carlo simulation number 140.
Running Monte Carlo simulation number 150.
Running Monte Carlo simulation number 160.
Running Monte Carlo simulation number 170.
Running Monte Carlo simulation number 180.
Running Monte Carlo simulation number 190.
Running Monte Carlo simulation number 200.
Running Monte Carlo simulation number 210.
Running Monte Carlo simulation number 220.
Running Monte Carlo simulation number 230.
Running Monte Carlo simulation number 240.
Running Monte Carlo simulation number 250.
Running Monte Carlo simulation number 260.
Running Monte Carlo simulation number 270.
Running Monte Carlo simulation number 280.
Running Monte Carlo simulation number 290.
Running Monte Carlo simulation number 300.
Running Monte Carlo simulation number 310.
Running Monte Carlo simulation number 320.
Running Monte Carlo simulation number 330.
Running Monte Carlo simulation number 340.
Running Monte Carlo simulation number 350.
Running Monte Carlo simulation number 360.
Running Monte Carlo simulation number 370.
Running Monte Carlo simulation number 380.
Running Monte Carlo simulation number 390.
Running Monte Carlo simulation number 400.
Running Monte Carlo simulation number 410.
Running Monte Carlo simulation number 420.
Running Monte Carlo simulation number 430.
Running Monte Carlo simulation number 440.
Running Monte Carlo simulation number 450.
Running Monte Carlo simulation number 460.
Running Monte Carlo simulation number 470.
Running Monte Carlo simulation number 480.
Running Monte Carlo simulation number 490.

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
1,0.991298,1.026540,0.995605,0.984985,0.998935,1.009679,0.977044,1.005181,1.029804,0.989625,...,0.989715,0.997768,0.972765,1.000299,0.987678,1.004942,0.974658,0.992667,1.016023,1.015869
2,1.012996,1.052113,0.984253,0.994239,0.983746,1.034386,0.983057,1.019791,1.030367,0.971603,...,0.972660,0.993095,0.956699,1.000118,0.970464,1.007279,0.963951,0.991670,1.017372,1.010825
3,1.008961,1.067905,0.989092,1.014988,0.986926,1.005882,1.011542,0.997652,1.039572,0.961618,...,0.965410,1.003739,0.971897,1.017643,0.993883,0.975239,0.968059,1.001123,1.039713,1.014019
4,0.997409,1.070561,1.008614,1.041663,0.992618,0.982781,1.020964,0.984176,1.041943,0.945850,...,0.988876,0.994022,0.959399,1.006831,1.024093,0.954034,0.963796,1.001600,1.041296,1.022357
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5036,24.212415,38.249176,41.723762,47.945182,52.287666,19.327912,60.200107,17.375487,10.513330,103.428488,...,13.786256,29.799424,10.590865,30.328754,262.298050,22.196922,97.286868,105.167420,104.686913,6.304497
5037,23.845143,39.152545,42.309289,47.755640,52.833506,19.447430,60.651789,17.160010,10.378573,105.085207,...,13.907798,29.432727,10.555602,30.287024,273.120199,21.632654,98.422795,106.855824,104.880515,6.360012
5038,23.528366,39.133664,42.427519,47.625347,52.774326,19.162719,60.917287,16.870277,10.405377,107.786567,...,13.991780,29.339105,10.673890,30.830443,273.095598,21.553107,100.743052,107.064212,106.764691,6.435428
5039,23.656704,39.972619,41.868800,48.412247,52.254664,18.947041,61.001199,17.101746,10.701566,107.795845,...,14.053744,29.276410,10.604731,30.305534,266.014812,20.891848,100.462710,107.111941,104.946219,6.400472
5040,24.259691,41.121513,41.378840,49.336839,52.919358,18.862956,60.907973,17.285559,10.850339,107.499359,...,13.859485,29.101444,10.632001,30.443709,263.309395,20.629608,99.397304,108.788214,106.919028,6.362524

In [60]:
larrys_mc = MCSimulation(
    portfolio_data = larrys_ticker,
    weights = [.2, .2, .2, .2, .2],
    num_simulation = 500,
    num_trading_days = 252*20)

In [62]:
# Run a Monte Carlo simulation to forecast five years cumulative returns with 60% AT&T stock
larrys_mc.calc_cumulative_return()

Running Monte Carlo simulation number 0.
Running Monte Carlo simulation number 10.
Running Monte Carlo simulation number 20.
Running Monte Carlo simulation number 30.
Running Monte Carlo simulation number 40.
Running Monte Carlo simulation number 50.
Running Monte Carlo simulation number 60.
Running Monte Carlo simulation number 70.
Running Monte Carlo simulation number 80.
Running Monte Carlo simulation number 90.
Running Monte Carlo simulation number 100.
Running Monte Carlo simulation number 110.
Running Monte Carlo simulation number 120.
Running Monte Carlo simulation number 130.
Running Monte Carlo simulation number 140.
Running Monte Carlo simulation number 150.
Running Monte Carlo simulation number 160.
Running Monte Carlo simulation number 170.
Running Monte Carlo simulation number 180.
Running Monte Carlo simulation number 190.
Running Monte Carlo simulation number 200.
Running Monte Carlo simulation number 210.
Running Monte Carlo simulation number 220.
Running Monte Carlo simulation number 230.
Running Monte Carlo simulation number 240.
Running Monte Carlo simulation number 250.
Running Monte Carlo simulation number 260.
Running Monte Carlo simulation number 270.
Running Monte Carlo simulation number 280.
Running Monte Carlo simulation number 290.
Running Monte Carlo simulation number 300.
Running Monte Carlo simulation number 310.
Running Monte Carlo simulation number 320.
Running Monte Carlo simulation number 330.
Running Monte Carlo simulation number 340.
Running Monte Carlo simulation number 350.
Running Monte Carlo simulation number 360.
Running Monte Carlo simulation number 370.
Running Monte Carlo simulation number 380.
Running Monte Carlo simulation number 390.
Running Monte Carlo simulation number 400.
Running Monte Carlo simulation number 410.
Running Monte Carlo simulation number 420.
Running Monte Carlo simulation number 430.
Running Monte Carlo simulation number 440.
Running Monte Carlo simulation number 450.
Running Monte Carlo simulation number 460.
Running Monte Carlo simulation number 470.
Running Monte Carlo simulation number 480.
Running Monte Carlo simulation number 490.

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
1,0.990050,0.982186,0.994961,0.987008,1.036021,1.003458,1.005515,0.992524,0.971473,1.021060,...,0.996367,0.990370,1.024808,1.016013,1.005449,1.008004,1.018160,1.018707,0.996569,1.012702
2,0.985016,0.991731,1.006606,0.980951,1.007274,1.014441,1.010964,0.983424,0.975743,1.014607,...,1.002673,0.984661,1.009014,1.039173,1.042644,1.029733,0.991780,1.021487,1.013007,0.997175
3,0.991743,0.982658,0.978160,0.977799,1.043292,1.012830,1.006863,1.003392,0.954499,1.017936,...,0.991579,1.003354,1.005375,1.038430,1.037413,1.044875,0.976060,1.058851,0.995667,0.983059
4,1.004018,0.995190,0.957062,0.972551,1.063108,0.998295,0.969025,1.003105,0.966317,0.983521,...,0.983457,1.024443,1.014043,1.057294,1.044821,1.020706,0.963137,1.040880,0.997609,0.979287
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5036,949.085665,738.754228,62.189771,64.858797,57.842042,243.651251,1820.141492,176.740329,143.440173,883.942757,...,99.308539,113.606768,910.164494,296.465598,1556.495413,185.145296,1583.957367,167.796468,1102.215087,510.065180
5037,943.913099,754.893661,61.173481,64.416092,57.303004,236.644442,1862.653559,175.574171,146.888928,873.272440,...,98.530280,114.853871,906.209637,300.093958,1477.867765,187.938560,1535.211830,165.611551,1087.692281,512.937039
5038,930.704652,756.934420,63.509444,66.687908,57.507062,239.474915,1834.161394,180.710453,149.068563,866.881414,...,98.555539,118.409245,893.895834,299.166343,1483.200522,189.290634,1508.844634,172.733084,1088.944320,502.454357
5039,915.944885,777.031930,63.733260,68.863247,57.427850,237.262470,1879.610408,177.965149,147.427578,877.507443,...,101.462677,118.250814,909.380880,294.401934,1478.601812,191.983155,1510.824658,174.793349,1094.105019,503.034146
5040,926.844127,783.654923,63.174935,70.385571,57.003314,233.249248,1866.348308,172.052538,147.682154,879.648327,...,100.060392,119.148463,931.021549,296.881802,1501.524735,194.168673,1520.351353,175.131276,1095.385329,500.283429

In [ ]:
# Define Panel Visualization Functions
def daily_returns():
    """Ark ETF's Daily Returns"""
    
    # YOUR CODE HERE!
    arkf_close = arkf_data['Close']
    arkk_close = arkk_data['Close']
    arkq_close = arkq_data['Close']
    arkf_daily_returns = pd.DataFrame(arkf_close.pct_change())
    arkk_daily_returns = pd.DataFrame(arkk_close.pct_change())
    arkq_daily_returns = pd.DataFrame(arkq_close.pct_change())
    arkf_daily_returns1 = arkf_daily_returns.rename(columns={'Close': 'ARKF'})
    arkk_daily_returns1 = arkk_daily_returns.rename(columns={'Close': 'ARKK'})
    arkq_daily_returns1 = arkq_daily_returns.rename(columns={'Close': 'ARKQ'})
    etf_df = pd.concat([arkf_daily_returns1, arkk_daily_returns1, arkq_daily_returns1], axis = 'columns', join = 'inner').dropna()
    larry_return_data = larry_portfolio_df[1:]
    weighted_returns = (larry_weights * larry_return_data)
    Larry_port_ret = pd.DataFrame(weighted_returns.sum(axis=1))
    larry_port_return = Larry_port_ret.rename(columns ={ 0 :"Larry's Returns"})
    joe_fidelity_return_data = joe_fidelity_portfolio_df[1:]
    weighted_returns_joe = (joe_weights * joe_fidelity_return_data)
    joe_fidelity_port_ret = pd.DataFrame(weighted_returns_joe.sum(axis=1))
    joe_fidelity_port_return = joe_fidelity_port_ret.rename(columns ={ 0 :"Joe's fidelity Returns"})
    combined_df = pd.concat([etf_df, larry_port_return, joe_fidelity_port_return], join = 'inner', axis = 'columns')
    combined_plot = combined_df.plot(title = 'All Daily Returns', figsize =(15,10))
    return combined_plot
def cumulative_returns():
    """Cumulative Returns"""
    
    # YOUR CODE HERE!
    combined_cumulative = (1 + combined_df).cumprod()
    combined_cumulative_plot = combined_cumulative.plot(title = 'Cumulative Returns', figsize =(15,10))
    return combined_cumulative_plot


def joe_simulation():
    """Joe's Simulated returns"""
    
    # YOUR CODE HERE
    joes_line_plot = joes_MC_even_dist.plot_simulation()
    return joes_line_plot


def larry_simulation():
    """Larry's Simulated returns"""
    
    # YOUR CODE HERE!
    larrys_line_plot = larrys_mc.plot_simulation()
    return larrys_line_plot



def joe_confidence_interval():
    """Joes probability distribution and confidence intervals"""

    # YOUR CODE HERE!
    joes_dist_plot = joes_MC_even_dist.plot_distribution()
    return joes_dist_plot

def larry_confidence_interval():
    """Larry's probability distribution and confidence intervals."""   
    
    # YOUR CODE HERE!
    larrys_dist_plot = larrys_mc.plot_distribution()

    return larrys_dist_plot

In [ ]:
# Create a Title for the Dashboard
# YOUR CODE HERE!
Portfolio_Analysis_dashboard = '# How does the average joe stack up to an ETF'

# Create a tab layout for the dashboard
# YOUR CODE HERE!
Portfolio_Analysis_dashboard = pn.Tabs(
    ("Ark ETF's Daily Returns", daily_returns()), ("Cumulative Returns", cumulative_returns()), ("Joe's Simulated returns", joe_simulation()),( "Larry's Simulated returns", larry_simulation()), ("Joes probability distribution and confidence intervals",joe_confidence_interval()), ("Joes probability distribution and confidence intervals", joe_confidence_interval()), ("Larry's probability distribution and confidence intervals.", larry_confidence_interval()), ("Parallel Categories Plot", parallel_categories()), ("Neighborhood Map", neighborhood_map()),("Sunburst Plot", sunburst())  
)

# Create the dashboard
# YOUR CODE HERE!
city_living_dashboard